DROP TABLE IF EXISTS "ORDER";
DROP TABLE IF EXISTS "ORDER_2";

CREATE TABLE "ORDER" (
  "FROM" INTEGER,
  "COL_DECIMAL" DECIMAL(4,3),
  "COL_VARCHAR" VARCHAR(10),
  "COL_DATE" DATE,
  "COL_TIMESTAMP" TIMESTAMP,
  "COL_TIME" TIME,
  "COL_JSON" JSON,
  "COL_BOOLEAN" BOOLEAN
);

CREATE TABLE "ORDER_2" (
  "FROM" INTEGER,
  "COL_DECIMAL" DECIMAL(4,3),
  "COL_VARCHAR" VARCHAR(10),
  "COL_DATE" DATE,
  "COL_TIMESTAMP" TIMESTAMP,
  "COL_TIME" TIME,
  "COL_JSON" JSON,
  "COL_BOOLEAN" BOOLEAN
);
